name: Notificación a ntfy.sh

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-notify:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run hello.js
        run: node hello.js

   
      - name: Send ntfy notification
        run: |
          curl -H "Title: CI - Push a main" \
               -d "Se hizo push a main en $GITHUB_REPOSITORY por $GITHUB_ACTOR. Commit: $GITHUB_SHA" \
               https://ntfy.sh/devops-itla
